/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        trabzonBlue: "#38b6ff",
        trabzonBordo: "#8A1538",
        current: "currentColor",
        transparent: "transparent",
        white: "#FFFFFF",
        black: "#1C2434",
        "black-2": "#010101",
        body: "#64748B",
        bodydark: "#AEB7C0",
        bodydark1: "#DEE4EE",
        bodydark2: "#8A99AF",
        bodydark3: "#7C8A9E",
        primary: "#3C50E0",
        primaryHover: "#2C3FD1",
        linkColor: "#646cff",
        secondary: "#80CAEE",
        stroke: "#E2E8F0",
        grayC: "#EFF4FB",
        graydark: "#515764",
        "gray-2": "#F7F9FC",
        "gray-3": "#FAFAFA",
        whiten: "#F1F5F9",
        whiter: "#F5F7FD",
        boxdark: "#24303F",
        "boxdark-2": "#1A222C",
        strokedark: "#2E3A47",
        "form-strokedark": "#3d4d60",
        "form-input": "#1d2a39",
        "meta-1": "#DC3545",
        "meta-2": "#EFF2F7",
        "meta-3": "#10B981",
        "meta-4": "#515764",
        "meta-5": "#259AE6",
        "meta-6": "#FFBA00",
        "meta-7": "#FF6766",
        "meta-8": "#F0950C",
        "meta-9": "#E5E7EB",
        "meta-10": "#0FADCF",
        success: "#219653",
        danger: "#D34053",
        warning: "#FFA70B",
        foxColor: "#F56E1A",
        foxColor2: "#F37E36",
        foxColorHover: "#DC6114",
        googleBlue: "#4285F4",
        navyBlue: "#0F0782",
        darkSuccess: "#177B42",
        usgreen: "#0C5460",
        uslightblue: "#9acfea",
        usdarkblue: "#265a88",
        "gray-4": "#808080",
        lightgray: "#cbcbcb",
        darkinput: "#1f2937",
        darkinputborder: "#4b5563",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Helvetica",
          "Arial",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
        ],
        inter: ["Inter", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      animation: {
        'slide-in': 'slideIn 0.5s ease-out',
      },
      keyframes: {
        slideIn: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
    },
  },
  safelist: [
    "group-hover:opacity-100",
    "opacity-0",
    "opacity-100",
    "z-10",
    "z-50",
    "z-[999]",
    "left-full",
    "ml-2",
    "top-1/2",
    "-translate-y-1/2",
  ],
  plugins: [require("@tailwindcss/typography")],
};
