export const dummyTasks = [
    {
      id: "t1",
      title: "Design landing page",
      description: "Create a responsive landing page with dark mode support.",
      status: "To-do",
      tags: ["frontend", "ui"],
      project: "Marketing Website",
      createdAt: "2025-04-01T10:00:00.000Z",
    },
    {
      id: "t2",
      title: "Implement user authentication",
      description: "Setup Firebase auth for login and registration.",
      status: "In Progress",
      tags: ["firebase", "auth"],
      project: "Backend Integration",
      createdAt: "2025-04-02T11:30:00.000Z",
    },
    {
      id: "t3",
      title: "Write unit tests for Tasks feature",
      description: "Cover reducer and UI interactions for the tasks module.",
      status: "In Review",
      tags: ["testing", "redux"],
      project: "QA",
      createdAt: "2025-04-03T14:45:00.000Z",
    },
    {
      id: "t4",
      title: "Optimize image loading",
      description: "Use next-gen image formats and lazy loading for faster load times.",
      status: "Done",
      tags: ["performance", "images"],
      project: "Frontend Optimization",
      createdAt: "2025-04-04T09:00:00.000Z",
    },
    {
      id: "t5",
      title: "Archive old tasks",
      description: "Move completed tasks from March to the archive.",
      status: "Archived",
      tags: ["maintenance", "cleanup"],
      project: "Housekeeping",
      createdAt: "2025-04-05T16:15:00.000Z",
    },
  ];