export const dummyCandidates = [
  {
    id: "1",
    name: "Yunus YILDIZ",
    position: "Full-Stack Developer",
    status: "Interviewed",
    tags: ["remote", "junior", "qualified", "first"],
    createdAt: "2024-10-10T12:00:00Z",
  },
  {
    id: "2",
    name: "Liam Chen",
    position: "UI/UX Designer",
    status: "Rejected",
    tags: ["full-time", "hybrid"],
    createdAt: "2024-10-11T10:30:00Z",
  },
  {
    id: "3",
    name: "Noah Müller",
    position: "Backend Developer",
    status: "Rejected",
    tags: ["onsite", "contract"],
    createdAt: "2024-10-12T08:15:00Z",
  },
  {
    id: "4",
    name: "Alice Morgan",
    position: "Frontend Developer",
    status: "Pending",
    tags: ["remote", "junior"],
    createdAt: "2024-10-10T12:00:00Z",
  },
  {
    id: "5",
    name: "John Doe",
    position: "DevOps Engineer",
    status: "To-do",
    tags: ["remote", "mid", "linux"],
    createdAt: "2024-10-13T09:45:00Z",
  },
  {
    id: "6",
    name: "Jane Dore",
    position: "Product Manager",
    status: "Pending",
    tags: ["full-time", "agile", "english"],
    createdAt: "2024-10-14T11:20:00Z",
  },
];